# Inserts a blank line between shell prompts
add_newline = false

# A minimal left prompt
format = """$directory
$character"""

# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[aws]
disabled = true